const citiesOption = [
  "New York",
  "Tokyo",
  "London",
  "Rome",
  "Sydney",
  "Beijing",
  "Cairo",
  "Moscow",
  "Berlin",
  "Dubai",
  "Paris",
  "Barcelona",
  "Istanbul",
  "Rio de Janeiro",
  "Toronto",
  "Mumbai",
  "Bangkok",
  "Cape Town",
  "Amsterdam",
  "Vienna",
  "Singapore",
  "Hong Kong",
  "Seoul",
  "Buenos Aires",
  "Mexico City",
  "Lisbon",
  "Prague",
  "Athens",
  "Stockholm",
  "Oslo",
  "Helsinki",
  "Copenhagen",
  "Dublin",
  "Edinburgh",
  "Zurich",
  "Geneva",
  "Brussels",
  "Vancouver",
  "Montreal",
  "San Francisco",
  "Los Angeles",
  "Chicago",
  "Miami",
  "Las Vegas",
  "Washington D.C.",
  "Boston",
  "Seattle",
  "New Orleans",
  "Austin",
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Auckland",
  "Wellington",
  "Christchurch",
  "Queenstown",
  "Dunedin",
  "Cape Town",
  "Johannesburg",
  "Nairobi",
  "Casablanca",
  "Marrakech",
  "Cairo",
  "Luxor",
  "Istanbul",
  "Ankara",
  "Dubai",
  "Abu Dhabi",
  "Riyadh",
  "Jeddah",
  "Jerusalem",
  "Tel Aviv",
  "Amman",
  "Petra",
  "Beirut",
  "Doha",
  "Manama",
  "Muscat",
  "Kuwait City",
  "Colombo",
  "Kathmandu",
  "Dhaka",
  "Hanoi",
  "Ho Chi Minh City",
  "Phnom Penh",
  "Vientiane",
  "Yangon",
  "Bangkok",
  "Chiang Mai",
  "Kuala Lumpur",
  "Penang",
];

const apiBaseUrl =
  process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:3000/";

export { citiesOption, apiBaseUrl };
